import { PlanInterval } from '../models/plan.model';

export const defaultPlans = [
  {
    slug: 'free',
    name: 'Free Plan',
    description: 'Explore how Deen AI can help get closer to Allah',
    price: '0.00',
    currency: 'USD',
    interval: PlanInterval.MONTHLY,
    isPopular: false,
    isCustom: false,
    displayOrder: 1,
    tokenLimit: 5000,
    features: [
      'Quran Access',
      'Essential Daily Tools',
      'Limited Reflections Access',
      'Limited AI Chat (Basic)',
    ],
  },
  {
    slug: 'premium-monthly',
    name: 'Premium (Monthly)',
    description: 'Unlock Unlimited Deep Study',
    price: '110.00',
    currency: 'USD',
    interval: PlanInterval.MONTHLY,
    isPopular: false,
    isCustom: false,
    displayOrder: 2,
    tokenLimit: 1000000,
    features: [
      'Unlimited AI Chat',
      'Full Reflection Suite (Unlimited Access)',
      'Recitations & Qibla Finder',
      'Multi-Language Translations',
    ],
  },
  {
    slug: 'premium-yearly',
    name: 'Premium (Yearly)',
    description: 'Unlock Unlimited Deep Study',
    price: '1100.00',
    currency: 'USD',
    interval: PlanInterval.YEARLY,
    isPopular: true,
    isCustom: false,
    displayOrder: 3,
    tokenLimit: 1200000,
    features: [
      'Unlimited AI Chat',
      'Full Reflection Suite (Unlimited Access)',
      'Recitations & Qibla Finder',
      'Multi-Language Translations',
    ],
  },
  {
    slug: 'partnerships',
    name: 'Partnerships',
    description: 'Community & Content Collaboration',
    price: null,
    currency: 'USD',
    interval: PlanInterval.CUSTOM,
    isPopular: false,
    isCustom: true,
    displayOrder: 4,
    tokenLimit: 0,
    features: [
      'Target Audience',
      'Content Distribution',
      'Community Access',
      'Revenue Share Model',
    ],
  },
];
